LibraryManagementSysytem/Controllers/Books/BookController.cs
using BusinessLayer.DTOs.Books;
using BusinessLayer.Services.Books;
using LibraryManagementSysytem.ActionRequests.Books;
using LibraryManagementSysytem.VMs.Books;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSysytem.Controllers.Books
{
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly IBookService _BookService;

        public BookController(IBookService BookService)
        {
            _BookService = BookService;

        }

        //[HttpGet]
        //public async Task<IActionResult> Index()
        //{
        //    var BooksDTO = await _BookService.GetAllBooks();
        //    var BooksVM = BooksDTO.Select(b => (BookListVM)b).ToList();

        //    return View(BooksVM);

        //}

        //[HttpPost]
        public async Task<IActionResult> Index(string searchTerm)
        {
            var BooksDTO = await _BookService.Search(searchTerm);

            var BooksVM = BooksDTO.Select(b => (BookListVM)b).ToList();


            return View(BooksVM);

        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBookActionRequest Book, IFormFile imageFile)
        {

            if (ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    // You can log or display the error message
                    Console.WriteLine(error.ErrorMessage);
                }


                #region UploadImageFile

                string UniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

                if (imageFile != null && imageFile.Length > 0)
                {

                    var filePath = Path.Combine(@".\wwwroot\Images\", UniqueFileName);
                    using (var filestraem = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.CopyTo(filestraem);
                    }
                }

                #endregion

                var AddBookDTO = new AddBookDTO

                {
                    Title = Book.Title,
                    Genre = Book.Genre,
                    Author = Book.Author,
                    Amount = Book.Amount,
                    DailyRent = Book.Daily_Rent,
                    LibrarianID = Book.LibrarianID_FK,
                    Image = UniqueFileName
                };
                await _BookService.AddBook(AddBookDTO);
                TempData["SuccessMessage"] = "Book added successfully!";
                return RedirectToAction(nameof(Index));

            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var BookDTO = await _BookService.GetById(id);
            var BookVM = (BookDetailsVM)BookDTO;

            return View(BookVM);
        }

        [HttpGet]
        public async Task<IActionResult> Update()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateBookActionRequest updateBook, IFormFile imageFile)
        {

            var BookToUpdate = await _BookService.GetById(updateBook.ID);

            if (ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    // You can log or display the error message
                    Console.WriteLine(error.ErrorMessage);
                }
                #region UploadImageFile

                string UniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

                if (imageFile != null && imageFile.Length > 0)
                {

                    var filePath = Path.Combine(@".\wwwroot\Images\", UniqueFileName);
                    using (var filestraem = new FileStream(filePath, FileMode.Create))
                    {
                        imageFile.CopyTo(filestraem);
                    }
                }

                #endregion
                BookToUpdate = new BookDetailsDTO()
                {
                    ID = updateBook.ID,
                    Title = updateBook.Title,
                    Genre = updateBook.Genre,
                    Author = updateBook.Author,
                    Amount = updateBook.Amount,
                    Daily_Rent = updateBook.Daily_Rent,
                    Image = UniqueFileName,
                    LibrarianID = updateBook.LibrarianID_FK
                };
                await _BookService.UpdateBook(BookToUpdate);
                await _BookService.SaveChanges();
                TempData["SuccessMessage"] = "Book Updated successfully!";
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public async Task<IActionResult> Remove(int id)
        {
            await _BookService.DeleteBookById(id);
            return RedirectToAction(nameof(Index));
            return View();
        }
    }
}

LibraryManagementSysytem/Controllers/RoleController.cs
using DataAccessLayer.Entities;
using LibraryManagementSysytem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSysytem.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly ILogger<RoleController> _logger;

        // Get, GetAll, Add, Update , Delete
        // Index, Create, Details, Edit, Delete

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager,ILogger<RoleController> logger)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string searchInput)
        {
            var roles = Enumerable.Empty<IdentityRole>();


            if (string.IsNullOrEmpty(searchInput))
            {
                roles = await _roleManager.Roles.ToListAsync();
            }
            else
            {

                roles = await _roleManager.Roles.Where(U => U.Name
                                  .ToLower()
                                  .Contains(searchInput.ToLower()))
                                  .Select(R => new IdentityRole()
                                  {
                                      Id = R.Id,
                                      Name = R.Name
                                  }).ToListAsync();

            }

            return View(roles);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)

 
            {
                var role = new IdentityRole()
                {
                    Name = model.Name,
                };

                await _roleManager.CreateAsync(role);
                return RedirectToAction(nameof(Index));
            }


            return View(model);
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role is null)
                return NotFound(); // 404

               var roleViewmodel = new RoleViewModel
               {
                   Id = role.Id,
                   Name = role.Name,

               };

               return View(ViewName, roleViewmodel);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {

            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, RoleViewModel roleModel)
        {
            if (roleModel.Id != id)
                return NotFound(); // 404

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);


                    if (role is null)
                        return NotFound();

                    role.Name = roleModel.Name;
                    role.NormalizedName = roleModel.Name.ToUpper();

                    var result = await _roleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        _logger.LogInformation("Role Update Successfully");
                        return RedirectToAction("Index");
                    }
                    foreach (var item in result.Errors)
                        _logger.LogError(item.Description);




                }
                catch (Exception ex)
                {

                    _logger.LogError(ex.Message);
                }

            }
            return View(roleModel);
        }
        public async Task<IActionResult> Delete(string id)
        {


            var role = await _roleManager.FindByIdAsync(id);
            if (role is null)
                return NotFound(); // 404


            var result = await _roleManager.DeleteAsync(role);

            if (result.Succeeded)

                return RedirectToAction(nameof(Index));

            foreach (var item in result.Errors)
                _logger.LogError(item.Description);


            return View("Index");
        }

        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            ViewData["RoleId"] = roleId;

            var usersInRole = new List<UsersInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                var userInRole = new UsersInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;

                }
                usersInRole.Add(userInRole);
            }

            return View(usersInRole);

        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UsersInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser is not null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                        }
                    }

                }
                return RedirectToAction(nameof(Update), new { id = roleId });
            }


            return View(users);


        }
    }
}

LibraryManagementSysytem/Controllers/TransactionBController.cs
using BusinessLayer.DTOs.Transactions;
using BusinessLayer.Services.Tranactions;
using LibraryManagementSysytem.ActionRequests.Transactions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;

namespace LibraryManagementSysytem.Controllers
{
    public class TransactionBController : Controller
    {

        private readonly ITranactionService _transactionService;
        public TransactionBController(ITranactionService transactionService)
        {
            _transactionService = transactionService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> create(CreateTransActionBActionRequest transaction)
        {
            if (ModelState.IsValid)
            { 
                AddTransactionDTO transactionDTO = new AddTransactionDTO()
                {
                    Total_Cost       = transaction.Total_Cost,
                    CheckOut_Date    = transaction.CheckOut_Date,
                    Due_Date         = transaction.Due_Date,
                    OverDueDate_Days = transaction.OverDueDate_Days,
                    Return_Date      = transaction.Return_Date,
                    LibrarianID_FK   = transaction.LibrarianID_FK,
                    MemberID_FK      = transaction.MemberID_FK,
                  

                };
            await _transactionService.AddTransaction(transactionDTO);
            TempData["Success"] = "تم الإضافة بنجاح";

            return RedirectToAction("Index");
            }
            return View();
        }
    }
}

LibraryManagementSysytem/Controllers/UserController.cs
using DataAccessLayer.Entities;
using LibraryManagementSysytem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSysytem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ILogger _logger;

        public UserController(UserManager<AppUser> userManager, ILogger<UserController> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string searchInput)
        {
            //var users = Enumerable.Empty<RoleUpdateViewModel>();
            List<AppUser> users;
            if (string.IsNullOrEmpty(searchInput))
                users = await _userManager.Users.ToListAsync();
            else
                users = await _userManager.Users.Where(U => U.NormalizedEmail.Trim()
                .Contains(searchInput.ToUpper().Trim())).ToListAsync();
     

            return View(users);
        }

        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user is null)
                return NotFound(); // 404

            if (ViewName == "Update")
            {
                var userviewmdel = new UserViewModel
                {
                    Id= user.Id,
                    UserName= user.UserName,
                    //Email=userFromDb.Email

                };
                return View(ViewName, userviewmdel);
            }

            else
                return View(ViewName, user);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {

            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, UserViewModel _user)
        {
            if (_user.Id != id)
                return NotFound(); // 404

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    if (user is null)
                        return NotFound();

                    user.UserName = _user.UserName;
                    user.NormalizedUserName = _user.UserName.ToUpper();
                    //user.FristName = _user.FristName;
                    //user.LastName = _user.LastName;
                    //user.Email = _user.Email;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        _logger.LogInformation("User Update Successfully");
                        return RedirectToAction("Index");
                    }
                    foreach (var item in result.Errors)
                        _logger.LogError(item.Description);
                    



                }
                catch (Exception ex)
                {

                    _logger.LogError(ex.Message);
                }

            }
            return View(_user);
        }
        public async Task<IActionResult> Delete(string id)
        {
            
            
                var userFromDb = await _userManager.FindByIdAsync(id);
                if (userFromDb is null)
                    return NotFound(); // 404


               var result= await _userManager.DeleteAsync(userFromDb);
               
            if (result.Succeeded) 
            
                return RedirectToAction(nameof(Index));

            foreach (var item in result.Errors)
                _logger.LogError(item.Description);




            return View("Index");
        }
    }
}

LibraryManagementSysytem/Views/Shared/_ActionButtonsPartialView.cshtml
@model string
<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Update" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

LibraryManagementSysytem/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative @ViewBag.Title Form</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2024 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

LibraryManagementSysytem/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> _signInManger
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagementSysytem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/LibraryManagementSysytem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script> <!-- SweetAlert2 -->

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryManagementSysytem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransactionB" asp-action="Create">New Tranaction</a>
                        </li>                        

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* @if (_signInManger.IsSignedIn(User) && User.IsInRole("Admin")) *@
                        @* { *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        @* }  *@
                       @* @if (_signInManger.IsSignedIn(User) && User.IsInRole("Admin")) *@
                        @* { *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Librarian" asp-action="Index">Librarian</a>
                            </li>
                        @* }  *@
                         @* @if (_signInManger.IsSignedIn(User)) *@
                        @* { *@
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                            </li>
                         @* }  *@
 

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryManagementSysytem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryManagementSysytem/Views/Shared/_Notifications.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
        
 
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Success"]');
    </script>


    <h2>@TempData["Error"]</h2>
}