LibraryManagementSysytem/Models/Librarian.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace LibraryManagementSysytem.Models
{
    public class Librarian
    {
        [Key]
        public int ID { get; set; }

        [MaxLength(100)]
        [Required]
        [DisplayName("First Name")]
        
        
        public string First_Name { get; set; }

        [MaxLength(100)]
        [Required]
        [DisplayName("Last Name")]

        public string Last_Name { get; set; }

        [MaxLength(100)]
        [EmailAddress]
        [Required]
        
        [DisplayName("Email Address")]
        
        public string Email { get; set; }

        [MaxLength(20)]
        [Required]
        [DisplayName("Phone Number")]
        //[Range(10,15 ,ErrorMessage ="Wrong Number")]
        public string Phone { get; set; }

    }

}

LibraryManagementSysytem/Controllers/Librarians/LibrarianController.cs
using DataAccessLayer.context;
using DataAccessLayer.Entities;
using LibraryManagementSysytem.Models;
using Microsoft.AspNetCore.Mvc;
using BusinessLayer.DTOs.Librarians;
using BusinessLayer.Services.Librarians;
using LibraryManagementSysytem.ActionRequests.Librarians;
using LibraryManagementSysytem.VMs.Librarians;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagementSysytem.Controllers.Librarians
{
    [Authorize(Roles = "Admin")]
    public class LibrarianController : Controller
    {

        private readonly ILibrarianService _librarianService;
        public LibrarianController(ILibrarianService librarianService)
        {
            _librarianService = librarianService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<LibrarianListDTO> librarianDTOs = await _librarianService.GetAll();
            var librarians = new List<LibrarianListVM>();
            foreach (var entity in librarianDTOs)
            {
                librarians.Add(new LibrarianListVM()
                {
                    ID = entity.ID,
                    First_Name = entity.First_Name,
                    Last_Name = entity.Last_Name,
                    Email = entity.Email,
                    Phone = entity.Phone
                });

            }
            return View("Index", librarians);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateLibrarianActionRequest librarian)
        {
            if (ModelState.IsValid)
            {
                AddLibrarianDTO librarianDTO = new AddLibrarianDTO()
                {
                    First_Name = librarian.First_Name,
                    Last_Name = librarian.Last_Name,
                    Email = librarian.Email,
                    Phone = librarian.Phone
                };
                await _librarianService.AddLibrarian(librarianDTO);
                //return RedirectToAction(nameof(Index));

                TempData["Success"] = "تم الإضافة بنجاح";

                return RedirectToAction("Index");

            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            LibrarianDetailsDTO librarianDTO = await _librarianService.GetbyId(id);

            if (librarianDTO == null)
            {
                return NotFound();
            }

            //var librarianVM = new LibrarianEditVM
            EditLibrarianDTO librarianDTO1 = new EditLibrarianDTO()
            {
                ID = librarianDTO.ID,
                First_Name = librarianDTO.First_Name,
                Last_Name = librarianDTO.Last_Name,
                Email = librarianDTO.Email,
                Phone = librarianDTO.Phone
            };



            return View(librarianDTO);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Librarian librarian)
        {
            if (ModelState.IsValid)
            {

                EditLibrarianDTO updatedLibrarian = new EditLibrarianDTO()
                {
                    ID = librarian.ID,
                    First_Name = librarian.First_Name,
                    Last_Name = librarian.Last_Name,
                    Email = librarian.Email,
                    Phone = librarian.Phone
                };
                await _librarianService.UpdateLibrarian(librarian);
                TempData["Success"] = "تم التعديل بنجاح";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            var librarianDTO = await _librarianService.GetbyId(id);

            if (librarianDTO == null)
            {
                return NotFound();
            }

            //var librarianVM = new LibrarianEditVM
            LibrarianDetailsDTO librarianDTO1 = new LibrarianDetailsDTO()
            {
                ID = librarianDTO.ID,
                First_Name = librarianDTO.First_Name,
                Last_Name = librarianDTO.Last_Name,
                Email = librarianDTO.Email,
                Phone = librarianDTO.Phone
            };



            return View(librarianDTO);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteLibrarian(int id)
        {

            if (ModelState.IsValid)
            {

                await _librarianService.DeleteLibrarian(id);
                TempData["Success"] = "تم الحذف بنجاح";
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}
//***********************************************************************************

//    public IActionResult Delete(int? id)
//    {
//        if (id == null || id == 0)
//        {
//            return NotFound();
//        }
//        Librarian? LibrarianfromDB = _librarianService.DeleteLibrarian(id);

//        if (LibrarianfromDB == null)
//        {
//            return NotFound();
//        }
//        return View(LibrarianfromDB);
//    }



//    [HttpPost, ActionName("Delete")]
//    public async Task<IActionResult> DeleteConfirmed(int? id)
//    {
//        if (id == null)
//        {
//            return NotFound();
//        }

//        await _librarianService.DeleteLibrarian((int)id);
//        TempData["Success"] = "تم الحذف بنجاح";
//        return RedirectToAction("Index");
//    }
//}

LibraryManagementSysytem/Views/Librarian/Create.cshtml
@using LibraryManagementSysytem.ActionRequests.Librarians;

@model CreateLibrarianActionRequest
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Create Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">

        <form method="post" class="row">
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary">ِCreate</button>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>
    </div>


</div>

LibraryManagementSysytem/Views/Librarian/Delete.cshtml
@using DataAccessLayer.Entities
@using BusinessLayer.DTOs.Librarians

@{
    ViewData["Title"] = "Edit";
}

@model LibrarianDetailsDTO

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Delete Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" disabled class="form-control" id="inputFirstName">

            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" disabled class="form-control" id="inputLastName">


            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" disabled type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>


            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" disabled class="form-control" id="inputPhone">


            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a asp-controller="Librarian" asp-action="Delete" class="btn btn-secondary border form-control"></a>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>

    </div>

LibraryManagementSysytem/Views/Librarian/Edit.cshtml
@using DataAccessLayer.Entities
@using BusinessLayer.DTOs.Librarians
@{
    ViewData["Title"] = "Edit";
}


@model LibrarianDetailsDTO
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Edit Librarian</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
   
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>


                <div class="col-6 col-md-3">
                    <a asp-controller="Librarian" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>


    </div>

LibraryManagementSysytem/Views/Librarian/Index.cshtml
@using DataAccessLayer.Entities
@using LibraryManagementSysytem.VMs.Librarians
@model List<LibrarianListVM>

<script type="text/javascript">
    function confirmDelete() {
        return confirm("Are you sure you want to delete this librarian?");
    }

    function confirmEdit() {
        return confirm("Are you sure you want to edit this librarian?");
    }
</script>


<div class="container">
    
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Librarian List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Librarian" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Librarian
            </a>
        </div>
    </div>
<table class="table table-hover table-dark">
    <thead>
        <tr>

            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col"></th>
            
            
        </tr>
    </thead>
    <tbody>
        @foreach (var Lib in Model.OrderBy(u=>u.First_Name))
        {
            <tr>

                <td>@Lib.First_Name  @Lib.Last_Name</td>
                <td>@Lib.Email</td>
                <td>@Lib.Phone</td>
@*                 <td> 
                    <div>
                            <a href="@Url.Action("Edit", new { id = Lib.ID })" onclick="return confirmEdit();">Edit</a> |
                            <a href="@Url.Action("Delete", new { id = Lib.ID })" onclick="return confirmDelete();">Delete</a>
                    </div>
                </td> *@
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Librarian" asp-action="Edit" asp-route-id="@Lib.ID" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                        </a>
                            <a asp-controller="Librarian" asp-action="Delete" asp-route-id="@Lib.ID" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3-fill"></i>Delete
                        </a>
                    </div>

                </td>

            </tr>
        }


    </tbody>
</table>
</div>