LibraryManagementSysytem/Controllers/Members/MemberController.cs
using BusinessLayer.DTOs;
using BusinessLayer.DTOs.Members;
using BusinessLayer.Services;
using BusinessLayer.Services.Members;
using DataAccessLayer.Entities;
using LibraryManagementSysytem.ActionRequests.Members;
using LibraryManagementSysytem.Models;
using LibraryManagementSysytem.VMs.Members;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSysytem.Controllers.Members
{
    public class MemberController : Controller
    {
        //    private readonly IMemberService _memberService;
        private readonly IMemberService _memberService;
        public MemberController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<MemberListDTO> memberDTOs = await _memberService.GetAll();
            var members = new List<MemberListVM>();
            foreach (var entity in memberDTOs)
            {
                members.Add(new MemberListVM()
                {
                    ID = entity.ID,
                    First_Name = entity.First_Name,
                    Last_Name = entity.Last_Name,
                    Email = entity.Email,
                    Phone = entity.Phone
                });

            }
            return View("Index", members);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMemberActionRequest member1)
        {
            if (ModelState.IsValid)
            {
                AddMemberDTO memberDTO = new AddMemberDTO()
                {
                    First_Name = member1.First_Name,
                    Last_Name = member1.Last_Name,
                    Email = member1.Email,
                    Phone = member1.Phone
                };
                await _memberService.AddMember(memberDTO);


                TempData["Success"] = "تم الإضافة بنجاح";

                return RedirectToAction("Index");

            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            MemberDetailsDTO memberDTO = await _memberService.GetbyId(id);

            if (memberDTO == null)
            {
                return NotFound();
            }


            EditMemberDTO memberDTO1 = new EditMemberDTO()
            {
                ID = memberDTO.ID,
                First_Name = memberDTO.First_Name,
                Last_Name = memberDTO.Last_Name,
                Email = memberDTO.Email,
                Phone = memberDTO.Phone
            };



            return View(memberDTO);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Member member2)
        {
            if (ModelState.IsValid)
            {

                EditMemberDTO updatedLibrarian = new EditMemberDTO()
                {
                    ID = member2.ID,
                    First_Name = member2.First_Name,
                    Last_Name = member2.Last_Name,
                    Email = member2.Email,
                    Phone = member2.Phone
                };
                await _memberService.UpdateMember(member2);
                TempData["Success"] = "تم التعديل بنجاح";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            var memberDTO2 = await _memberService.GetbyId(id);

            if (memberDTO2 == null)
            {
                return NotFound();
            }


            MemberDetailsDTO memberDTO1 = new MemberDetailsDTO()
            {
                ID = memberDTO2.ID,
                First_Name = memberDTO2.First_Name,
                Last_Name = memberDTO2.Last_Name,
                Email = memberDTO2.Email,
                Phone = memberDTO2.Phone
            };



            return View(memberDTO2);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteMember(int id)
        {

            if (ModelState.IsValid)
            {

                await _memberService.DeleteMember(id);
                TempData["Success"] = "تم الحذف بنجاح";
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

LibraryManagementSysytem/Views/Member/Create.cshtml
@using LibraryManagementSysytem.ActionRequests.Members
@model CreateMemberActionRequest
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Create Member</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">

        <form method="post" class="row">
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Member" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>
    </div>


</div>

LibraryManagementSysytem/Views/Member/Delete.cshtml
@using DataAccessLayer.Entities
@using BusinessLayer.DTOs.Members
@{
    ViewData["Title"] = "Edit";
}

@model MemberDetailsDTO

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Delete Member</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" disabled class="form-control" id="inputFirstName">

            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" disabled class="form-control" id="inputLastName">


            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" disabled type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>


            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" disabled class="form-control" id="inputPhone">


            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a asp-controller="Member" asp-action="Delete" class="btn btn-secondary border form-control"></a>
                </div>

                <div class="col-6 col-md-3">
                    <a asp-controller="Member" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>

    </div>

LibraryManagementSysytem/Views/Member/Edit.cshtml
@using DataAccessLayer.Entities
@using BusinessLayer.DTOs.Members
@{
    ViewData["Title"] = "Edit";
}


@model MemberDetailsDTO
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ms-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">Edit Member</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="ID" hidden />
            <div class="form-group">
                <div asp-validation-summary="All"></div>
                <label asp-for="First_Name" for="inputFirstName"></label>
                <input asp-for="First_Name" class="form-control" id="inputFirstName">
                <span asp-validation-for="First_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Last_Name" for="inputLastName"></label>
                <input asp-for="Last_Name" class="form-control" id="inputLastName">
                <span asp-validation-for="Last_Name" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Email" for="exampleInputEmail1"></label>
                <input asp-for="Email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                <span asp-validation-for="Email" class="text-danger"></span>

            </div>

            <div class="form-group">
                <label asp-for="Phone" for="inputPhone"></label>
                <input asp-for="Phone" class="form-control" id="inputPhone">
                <span asp-validation-for="Phone" class="text-danger"></span>

            </div>


            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <div class="row">
                <div class="col-6 col-md-3">

                    <button type="submit" class="btn btn-primary">Update</button>
                </div>


                <div class="col-6 col-md-3">
                    <a asp-controller="Member" asp-action="Index" class="btn btn-secondary border form-control">
                        Back To List
                    </a>
                </div>
            </div>

        </form>


    </div>

LibraryManagementSysytem/Views/Member/Index.cshtml
@using DataAccessLayer.Entities
@using LibraryManagementSysytem.VMs.Members
@model List<MemberListVM>

<script type="text/javascript">
    function confirmDelete() {
        return confirm("Are you sure you want to delete this member?");
    }

    function confirmEdit() {
        return confirm("Are you sure you want to edit this member?");
    }
</script>


<div class="container">

    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Member List
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Member" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>Create New Member
            </a>
        </div>
    </div>
    <table class="table table-hover table-dark">
        <thead>
            <tr>

                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col"></th>


            </tr>
        </thead>
        <tbody>
            @foreach (var mem in Model.OrderBy(u => u.First_Name))
            {
                <tr>

                    <td>@mem.First_Name  @mem.Last_Name</td>
                    <td>@mem.Email</td>
                    <td>@mem.Phone</td>
                    @*                 <td>
                <div>
                <a href="@Url.Action("Edit", new { id = Lib.ID })" onclick="return confirmEdit();">Edit</a> |
                <a href="@Url.Action("Delete", new { id = Lib.ID })" onclick="return confirmDelete();">Delete</a>
                </div>
                </td> *@
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Member" asp-action="Edit" asp-route-id="@mem.ID" class="btn btn-primary mx-2">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Member" asp-action="Delete" asp-route-id="@mem.ID" class="btn btn-danger mx-2">
                                <i class="bi bi-trash3-fill"></i>Delete
                            </a>
                        </div>

                    </td>

                </tr>
            }


        </tbody>
    </table>
</div>@{
}